create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,slug text not null unique,name text not null default 'Nombre de la Iglesia',handle text,bio text,logo_url text,accent_color text not null default '#d8b36a',background_style text not null default 'midnight',template text not null default 'elegant',palette jsonb not null default '{"accent":"#d8b36a","background":"#05080d","surface":"#111923","text":"#ffffff","muted":"#b8c1d0","primary":"#d8b36a"}'::jsonb,kicker text not null default '',values_text text not null default '',quote_text text not null default '',quote_verse text not null default '',contact_email text,contact_phone text,contact_address text,show_contact_email boolean not null default false,show_contact_phone boolean not null default false,show_contact_address boolean not null default false,featured_title text,featured_url text,featured_image_url text,footer_text text default '',published boolean not null default true,translations jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.links(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,title text not null,subtitle text,url text not null,icon text not null default 'link',sort_order integer not null default 0,active boolean not null default true,translations jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.profiles add column if not exists template text not null default 'elegant';
alter table public.profiles add column if not exists palette jsonb not null default '{"accent":"#d8b36a","background":"#05080d","surface":"#111923","text":"#ffffff","muted":"#b8c1d0","primary":"#d8b36a"}'::jsonb;
alter table public.profiles add column if not exists kicker text not null default '';
alter table public.profiles add column if not exists values_text text not null default '';
alter table public.profiles add column if not exists quote_text text not null default '';
alter table public.profiles add column if not exists quote_verse text not null default '';
alter table public.profiles add column if not exists contact_email text;
alter table public.profiles add column if not exists contact_phone text;
alter table public.profiles add column if not exists contact_address text;
alter table public.profiles add column if not exists show_contact_email boolean not null default false;
alter table public.profiles add column if not exists show_contact_phone boolean not null default false;
alter table public.profiles add column if not exists show_contact_address boolean not null default false;
alter table public.profiles alter column footer_text set default '';
alter table public.profiles enable row level security; alter table public.links enable row level security;
drop policy if exists "public profiles" on public.profiles; create policy "public profiles" on public.profiles for select using(published=true or auth.uid()=id);
drop policy if exists "public links" on public.links; create policy "public links" on public.links for select using((active=true and exists(select 1 from public.profiles p where p.id=profile_id and p.published=true)) or auth.uid()=profile_id);
drop policy if exists "owner profiles" on public.profiles; create policy "owner profiles" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
drop policy if exists "owner links" on public.links; create policy "owner links" on public.links for all using(auth.uid()=profile_id) with check(auth.uid()=profile_id);
create index if not exists links_profile_order_idx on public.links(profile_id,sort_order);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,slug,name,handle) values(new.id,'iglesia-'||substr(replace(new.id::text,'-',''),1,8),coalesce(new.raw_user_meta_data->>'name','Mi Iglesia'),'@miiglesia') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
