'use client';
import { useEffect,useState } from 'react';
import { supabaseBrowser } from '@/lib/supabase';
import type { Profile,LinkItem } from '@/lib/types';

export default function Admin(){
 const sb=supabaseBrowser();
 const [user,setUser]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[links,setLinks]=useState<LinkItem[]>([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[signup,setSignup]=useState(false),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false);
 async function load(u:any){setUser(u);if(u){const {data:p}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();setProfile(p);if(p){const {data:l}=await sb.from('links').select('*').eq('profile_id',p.id).order('sort_order');setLinks(l||[])}}setLoading(false)}
 useEffect(()=>{sb.auth.getUser().then(({data})=>load(data.user));const {data:{subscription}}=sb.auth.onAuthStateChange((_e,s)=>load(s?.user));return()=>subscription.unsubscribe()},[]);
 if(loading)return <main className="login"><div className="login-card">Cargando…</div></main>;
 async function auth(){const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});setMsg(r.error?.message||'Listo.');}
 if(!user)return <main className="login"><div className="login-card"><h1>Administrador</h1><p className="muted">Gestiona tu página de enlaces.</p><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></div><div className="field"><label>Contraseña</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></div><button className="btn btn-primary" style={{width:'100%'}} onClick={auth}>{signup?'Crear cuenta':'Entrar'}</button><button className="btn btn-secondary" style={{width:'100%',marginTop:9}} onClick={()=>setSignup(!signup)}>{signup?'Ya tengo cuenta':'Crear cuenta'}</button>{msg&&<p>{msg}</p>}</div></main>;
 if(!profile)return <main className="login"><div className="login-card"><h1>Perfil no encontrado</h1><p className="muted">Tu cuenta aún no tiene perfil. Se intentará crear automáticamente al registrarte; si el esquema aún no está aplicado, ejecuta <b>supabase/schema.sql</b> en Supabase.</p></div></main>;
 async function saveProfile(){const current=profile;if(!current)return;const {error}=await sb.from('profiles').update({...current}).eq('id',current.id);setMsg(error?.message||'Perfil guardado.')}
 async function uploadLogo(file:File){if(!profile)return;setUploading(true);setMsg('Subiendo logo…');const ext=file.name.split('.').pop()?.toLowerCase()||'png';const path=`${profile.id}/logo.${ext}`;const up=await sb.storage.from('assets').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up.error){setMsg(up.error.message);setUploading(false);return}const {data}=sb.storage.from('assets').getPublicUrl(path);const next={...profile,logo_url:data.publicUrl};setProfile(next);const {error}=await sb.from('profiles').update({logo_url:data.publicUrl}).eq('id',profile.id);setMsg(error?.message||'Logo actualizado.');setUploading(false)}
 async function saveLink(l:LinkItem,i:number){const current=profile;if(!current)return;const payload={title:l.title,subtitle:l.subtitle,url:l.url,icon:l.icon,sort_order:i,active:l.active,profile_id:current.id};const r=l.id?await sb.from('links').update(payload).eq('id',l.id):await sb.from('links').insert(payload).select().single();if(!r.error&&r.data){const n=[...links];n[i]=r.data;setLinks(n)}setMsg(r.error?.message||'Enlace guardado.')}
 async function add(){const current=profile;if(!current)return;setLinks([...links,{id:'',profile_id:current.id,title:'Nuevo enlace',subtitle:'',url:'https://',icon:'link',sort_order:links.length,active:true}])}
 return <main className="admin-page"><div className="admin-wrap"><header className="admin-head"><div><span className="eyebrow">IGLESIA LINKTREE</span><h1>Administrador</h1></div><button className="btn btn-secondary" onClick={()=>sb.auth.signOut()}>Salir</button></header>{msg&&<div className="success">{msg}</div>}
 <section className="panel"><h2>Perfil</h2><div className="grid2"><div className="field"><label>Nombre</label><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></div><div className="field"><label>Slug</label><input value={profile.slug} onChange={e=>setProfile({...profile,slug:e.target.value})}/></div><div className="field"><label>Handle</label><input value={profile.handle||''} onChange={e=>setProfile({...profile,handle:e.target.value})}/></div><div className="field"><label>Color</label><input value={profile.accent_color} onChange={e=>setProfile({...profile,accent_color:e.target.value})}/></div></div><div className="field"><label>Bio</label><textarea value={profile.bio||''} onChange={e=>setProfile({...profile,bio:e.target.value})}/></div><div className="field"><label>Logo de la iglesia</label><input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)uploadLogo(f)}}/>{profile.logo_url&&<img src={profile.logo_url} alt="Logo actual" style={{width:110,height:110,objectFit:'contain',marginTop:8,borderRadius:'50%',background:'#fff'}}/>}</div><button className="btn btn-primary" onClick={saveProfile}>Guardar perfil</button></section>
 <section className="panel"><div className="section-title"><h2>Enlaces</h2><button className="btn btn-primary" onClick={add}>+ Añadir</button></div>{links.map((l,i)=><div className="edit-card" key={i}><div className="field"><label>Título</label><input value={l.title} onChange={e=>{const n=[...links];n[i]={...l,title:e.target.value};setLinks(n)}}/></div><div className="field"><label>Subtítulo</label><input value={l.subtitle||''} onChange={e=>{const n=[...links];n[i]={...l,subtitle:e.target.value};setLinks(n)}}/></div><div className="field"><label>URL</label><input value={l.url} onChange={e=>{const n=[...links];n[i]={...l,url:e.target.value};setLinks(n)}}/></div><div className="field"><label>Icono</label><select value={l.icon} onChange={e=>{const n=[...links];n[i]={...l,icon:e.target.value};setLinks(n)}}><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="youtube">YouTube</option><option value="whatsapp">WhatsApp</option><option value="donation">Donaciones</option><option value="calendar">Eventos</option><option value="website">Web</option><option value="link">Enlace</option></select></div><button className="btn btn-primary" onClick={()=>saveLink(l,i)}>Guardar enlace</button></div>)}</section></div></main>}
