'use client';
export default function AdminPanelSkin(){
 return <style jsx global>{`
 .admin-page{min-height:100vh!important;padding:22px!important;background:#eef1f5!important;color:#17191d!important;color-scheme:light dark}
 .admin-wrap{width:min(1380px,100%)!important;margin:auto!important;display:grid!important;grid-template-columns:238px minmax(0,1fr)!important;grid-template-areas:"side head" "side notice" "side main";gap:0 24px!important;align-items:start}
 .admin-head{grid-area:head!important;margin:0!important;padding:4px 4px 20px!important;min-height:76px}.admin-head h1{font-size:30px!important;letter-spacing:-.04em!important;color:#17191d!important}.admin-head .muted{margin:5px 0 0!important;font-size:13px!important;color:#66707a!important}.admin-head-actions{display:flex;gap:9px;flex-wrap:wrap}.admin-head-actions .btn{background:#f9fafb!important;color:#222!important;border:1px solid #d8dde3!important;box-shadow:0 1px 2px rgba(0,0,0,.04)!important}
 .admin-nav{grid-area:side!important;position:sticky!important;top:18px!important;width:238px!important;min-height:calc(100vh - 36px)!important;padding:13px!important;border:1px solid #dce1e7!important;border-radius:18px!important;background:#18191b!important;box-shadow:0 16px 45px rgba(23,25,29,.12)!important;display:flex!important;flex-direction:column!important;gap:17px!important}
 .admin-nav:before{content:'IGLESIA LINKTREE';display:block;padding:9px 10px 8px;color:#fff;font-size:12px;font-weight:800;letter-spacing:.08em;border-bottom:1px solid rgba(255,255,255,.08);margin-bottom:1px}
 .nav-group{display:grid!important;gap:3px!important}.nav-group>span{padding:3px 10px 6px!important;color:#7f858d!important;font-size:9px!important;font-weight:800!important;letter-spacing:.15em!important}.nav-group button{width:100%!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;min-height:42px!important;padding:10px 11px!important;border:1px solid transparent!important;border-radius:10px!important;background:transparent!important;color:#b8bdc5!important;font-size:13px!important;font-weight:600!important;text-align:left!important;cursor:pointer!important}.nav-group button:hover{background:rgba(255,255,255,.06)!important;color:#fff!important}.nav-group button.active{background:#2a2b2e!important;border-color:rgba(255,255,255,.07)!important;color:#fff!important;box-shadow:inset 3px 0 0 #d8b36a!important}.nav-group button:before{width:22px!important;margin-right:7px!important;opacity:.75!important;text-align:center!important;font-size:13px!important}.nav-group:nth-of-type(1) button:nth-of-type(1):before{content:'⌂'}.nav-group:nth-of-type(1) button:nth-of-type(2):before{content:'↗'}.nav-group:nth-of-type(1) button:nth-of-type(3):before{content:'✦'}.nav-group:nth-of-type(1) button:nth-of-type(4):before{content:'★'}.nav-group:nth-of-type(2) button:before{content:'▣'}.nav-group:nth-of-type(3) button:before{content:'♟'}.nav-group:nth-of-type(4) button:before{content:'⚿'}
 .admin-main{grid-area:main!important;min-width:0!important}.admin-wrap>.success,.admin-wrap>.error{grid-area:notice!important;margin:0 0 12px!important}.panel{width:100%!important;margin:0 0 16px!important;padding:25px!important;border:1px solid #dce2e8!important;border-radius:16px!important;background:#f9fafb!important;box-shadow:0 2px 10px rgba(30,35,40,.035)!important}.panel h2{font-size:21px!important;letter-spacing:-.03em!important;margin:0!important;color:#17191d!important}.panel .muted{color:#707983!important}
 .section-title{padding-bottom:18px!important;margin-bottom:20px!important;border-bottom:1px solid #e6eaee!important}.section-title .muted{font-size:13px!important;margin-top:5px!important}.field{margin:0 0 15px!important;gap:6px!important}.field label{font-size:12px!important;font-weight:700!important;color:#59636d!important}
 input,textarea,select{background:#f5f7f9!important;border-color:#d8dee5!important;border-radius:10px!important;color:#17191d!important;min-height:44px!important;outline:none!important;transition:border-color .15s,box-shadow .15s!important}textarea{min-height:104px!important;resize:vertical!important}input:focus,textarea:focus,select:focus{border-color:#9ca7b2!important;box-shadow:0 0 0 3px rgba(80,90,105,.08)!important}
 .btn{min-height:42px!important;border-radius:10px!important;font-size:13px!important;font-weight:700!important}.btn-primary{background:#17191d!important;color:#fff!important;border-color:#17191d!important;box-shadow:none!important}.btn-secondary{background:#eef1f4!important;color:#25282d!important;border-color:#d8dee5!important}
 .grid2{gap:14px!important}.edit-card{padding:18px!important;margin:12px 0 0!important;border-radius:14px!important;background:#f4f6f8!important;border-color:#dce2e8!important}.edit-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-bottom:12px;margin-bottom:13px;border-bottom:1px solid #e4e8ec}.edit-card-head strong{font-size:15px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status-on,.status-off{font-size:11px;font-weight:800;padding:5px 8px;border-radius:999px;white-space:nowrap}.status-on{color:#1d7a4a;background:#e6f5ec}.status-off{color:#66707c;background:#e9edf1}.link-disabled{opacity:.62}.edit-actions{justify-content:flex-end!important;flex-wrap:wrap!important;padding-top:6px!important}
 .language-tabs{gap:6px!important}.language-tabs .language-circle{width:34px!important;height:34px!important;background:#eef1f4!important;color:#59616c!important;border-color:#d8dee5!important}.language-tabs .language-circle.active{background:#17191d!important;color:#fff!important;border-color:#17191d!important}
 .theme-editor{padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important}.qr-panel{display:grid!important;grid-template-columns:minmax(0,1fr) 260px!important;align-items:center!important}.qrbox{width:240px!important;min-height:240px!important;display:grid!important;place-items:center!important;border:1px dashed #cbd2da!important;border-radius:16px!important;background:#fff!important;color:#111!important}
 .member-list{display:grid!important;gap:8px!important}.member-row{position:relative;display:grid!important;grid-template-columns:42px minmax(0,1fr) auto!important;align-items:center!important;gap:12px!important;padding:12px!important;border:1px solid #dce2e8!important;border-radius:13px!important;background:#f4f6f8!important}.member-avatar{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:#e8ecf0;color:#343941}.member-info{min-width:0;display:grid;gap:3px}.member-info strong{font-size:14px;color:#22262b}.member-info span{font-size:12px;color:#77818b;overflow:hidden;text-overflow:ellipsis}.member-role select{min-width:145px}.primary-badge{display:inline-flex;align-items:center;min-height:40px;padding:0 11px;border-radius:10px;background:#e9edf1;color:#3d434b;font-size:11px;font-weight:800}.saving-mini{position:absolute;right:12px;bottom:-18px;font-size:10px;color:#7b838d}.role-help{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.role-help>div{padding:13px;border:1px solid #dce2e8;border-radius:12px;background:#f4f6f8}.role-help b,.role-help span{display:block}.role-help b{font-size:12px;color:#272b30}.role-help span{margin-top:4px;font-size:11px;line-height:1.5;color:#747c86}
 .admin-page .success{background:#e6f5ec!important;border:1px solid #cce5d7!important;color:#247447!important}.admin-page .error{background:#fff0f1!important;border:1px solid #f0cfd3!important;color:#9c303d!important}.admin-page .eyebrow{font-size:10px!important;letter-spacing:.18em!important;color:#737a83!important}.admin-page .muted{color:#707983!important}
 @media(prefers-color-scheme:dark){
  .admin-page{background:#090d12!important;color:#edf1f5!important}
  .admin-head h1{color:#f5f7fa!important}.admin-head .muted,.admin-page .muted{color:#9ca6b1!important}.admin-head-actions .btn{background:#141a21!important;color:#edf1f5!important;border-color:#29323b!important}
  .panel{background:#111820!important;border-color:#27313a!important;box-shadow:0 18px 45px rgba(0,0,0,.18)!important}.panel h2{color:#f5f7fa!important}.panel .muted{color:#9ca6b1!important}.section-title{border-color:#27313a!important}.field label{color:#aeb7c1!important}
  input,textarea,select{background:#0d1319!important;border-color:#2a343e!important;color:#f0f3f6!important}.field input::placeholder,.field textarea::placeholder{color:#68737e!important}input:focus,textarea:focus,select:focus{border-color:#667482!important;box-shadow:0 0 0 3px rgba(216,179,106,.10)!important}
  .btn-primary{background:#f0f3f6!important;color:#0b0f13!important;border-color:#f0f3f6!important}.btn-secondary{background:#171e26!important;color:#e8edf2!important;border-color:#2b353f!important}
  .edit-card,.member-row,.role-help>div{background:#0d141b!important;border-color:#29343e!important}.edit-card-head{border-color:#29343e!important}.member-info strong,.role-help b{color:#edf1f5!important}.member-info span,.role-help span{color:#8d98a3!important}.member-avatar{background:#18212a!important;color:#d6dde4!important}.primary-badge{background:#1b232c!important;color:#d8e0e7!important}.status-on{color:#79d39e!important;background:#123021!important}.status-off{color:#9da7b1!important;background:#1a222a!important}
  .language-tabs .language-circle{background:#171e26!important;color:#aeb7c1!important;border-color:#2b353f!important}.language-tabs .language-circle.active{background:#f0f3f6!important;color:#0b0f13!important;border-color:#f0f3f6!important}
  .qrbox{background:#f7f8fa!important;color:#111!important;border-color:#4a5661!important}
  .admin-page .success{background:#102a1c!important;border-color:#1e4b33!important;color:#8ee0ad!important}.admin-page .error{background:#32161a!important;border-color:#5b2a31!important;color:#ff9ea8!important}
 }
 @media(max-width:900px){
  .admin-page{padding:12px 12px 94px!important}.admin-wrap{display:block!important}
  .admin-nav{position:fixed!important;left:50%!important;bottom:10px!important;top:auto!important;transform:translateX(-50%)!important;z-index:100!important;width:calc(100% - 20px)!important;max-width:520px!important;min-height:0!important;height:68px!important;margin:0!important;padding:7px!important;border:1px solid #34363a!important;border-radius:20px!important;background:rgba(24,25,27,.97)!important;box-shadow:0 12px 38px rgba(0,0,0,.28)!important;display:grid!important;grid-template-columns:repeat(7,minmax(0,1fr))!important;gap:2px!important;overflow:visible!important;backdrop-filter:blur(18px)!important}
  .admin-nav:before{display:none!important}.nav-group{display:contents!important}.nav-group>span{display:none!important}
  .nav-group button{width:100%!important;min-width:0!important;height:54px!important;min-height:54px!important;padding:7px 2px!important;border:0!important;border-radius:14px!important;background:transparent!important;color:#aeb3bb!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:4px!important;font-size:9px!important;font-weight:700!important;line-height:1!important;text-align:center!important;white-space:nowrap!important}.nav-group button:hover{background:rgba(255,255,255,.06)!important;color:#fff!important}.nav-group button.active{background:#2c2e31!important;color:#fff!important;box-shadow:inset 0 2px 0 #d8b36a!important}.nav-group button:before{display:block!important;width:auto!important;height:18px!important;margin:0!important;opacity:1!important;font-size:19px!important;line-height:18px!important;font-weight:400!important}
  .nav-group:nth-of-type(1) button:nth-of-type(1):before{content:'⌂'}.nav-group:nth-of-type(1) button:nth-of-type(2):before{content:'↗'}.nav-group:nth-of-type(1) button:nth-of-type(3):before{content:'✦'}.nav-group:nth-of-type(1) button:nth-of-type(4):before{content:'★'}.nav-group:nth-of-type(2) button:before{content:'▣'}.nav-group:nth-of-type(3) button:before{content:'♟'}.nav-group:nth-of-type(4) button:before{content:'⚿'}
  .panel{padding:19px!important}.qr-panel{grid-template-columns:1fr!important}.qrbox{width:100%!important;min-height:190px!important}.role-help{grid-template-columns:1fr!important}.member-row{grid-template-columns:38px minmax(0,1fr)!important}.member-role{grid-column:2!important}.member-role select,.primary-badge{width:100%!important}
 }
 @media(max-width:620px){
  .admin-page{padding:10px 10px 94px!important}.admin-head{align-items:flex-start!important;flex-direction:column!important;padding-bottom:14px!important}.admin-head h1{font-size:24px!important}.admin-head-actions{width:100%!important}.admin-head-actions .btn{flex:1!important}.grid2{grid-template-columns:1fr!important}.section-title{align-items:flex-start!important;flex-direction:column!important}.edit-actions{justify-content:stretch!important}.edit-actions .btn{flex:1!important}.admin-nav{height:66px!important;bottom:8px!important;border-radius:19px!important}.nav-group button{height:52px!important;min-height:52px!important;font-size:8px!important}.nav-group button:before{font-size:18px!important}
 }
 `}</style>
}
