'use client';

export default function AdminPanelSkin(){
  return <style jsx global>{`
    /* Admin V2 — visual shell only; existing editing logic stays intact. */
    .admin-page{min-height:100vh!important;padding:24px!important;background:radial-gradient(circle at 10% 0%,rgba(216,179,106,.10),transparent 28%),radial-gradient(circle at 100% 70%,rgba(65,105,160,.10),transparent 30%),#080b12!important;color:#f8fafc}
    .admin-wrap{width:min(1280px,100%)!important;margin:auto!important;display:grid!important;grid-template-columns:230px minmax(0,1fr)!important;grid-template-areas:"side head" "side nav" "side main";gap:0 22px!important;align-items:start}
    .admin-head{grid-area:head!important;margin:0!important;padding:6px 2px 18px!important;min-height:74px}
    .admin-head h1{font-size:28px!important;letter-spacing:-.03em!important}.admin-head .muted{margin:4px 0 0!important;font-size:13px!important}.admin-head-actions{display:flex;gap:9px;flex-wrap:wrap}
    .admin-nav{grid-area:side!important;position:sticky!important;top:18px!important;width:230px!important;min-height:calc(100vh - 36px)!important;padding:14px!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:22px!important;background:rgba(15,20,30,.82)!important;backdrop-filter:blur(20px)!important;box-shadow:0 24px 70px rgba(0,0,0,.24)!important;display:flex!important;flex-direction:column!important;gap:5px!important}
    .admin-nav:before{content:'IGLESIA LINKTREE';display:block;padding:8px 10px 13px;color:#d8b36a;font-size:10px;font-weight:800;letter-spacing:.18em}
    .admin-nav button{width:100%!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;min-height:44px!important;padding:10px 12px!important;border:1px solid transparent!important;border-radius:12px!important;background:transparent!important;color:#aeb8c8!important;font-size:14px!important;font-weight:600!important;text-align:left!important;cursor:pointer!important}
    .admin-nav button:hover{background:rgba(255,255,255,.055)!important;color:#fff!important}.admin-nav button.active{background:rgba(216,179,106,.12)!important;border-color:rgba(216,179,106,.24)!important;color:#f1d18d!important;box-shadow:inset 3px 0 0 #d8b36a!important}
    .admin-nav button:nth-child(1):before{content:'◉'}.admin-nav button:nth-child(2):before{content:'↗'}.admin-nav button:nth-child(3):before{content:'✦'}.admin-nav button:nth-child(4):before{content:'★'}.admin-nav button:nth-child(5):before{content:'▣'}.admin-nav button:nth-child(6):before{content:'⚿'}.admin-nav button:before{width:24px;margin-right:7px;opacity:.75;text-align:center;font-size:14px}.admin-nav button.active:before{opacity:1}
    .admin-wrap>.success,.admin-wrap>.error{grid-area:nav!important;margin:0 0 12px!important}.admin-wrap>.panel{grid-area:main!important}
    .panel{width:100%!important;margin:0 0 16px!important;padding:24px!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:20px!important;background:rgba(15,20,30,.72)!important;box-shadow:0 18px 55px rgba(0,0,0,.18)!important}.panel h2{font-size:20px!important;letter-spacing:-.02em!important;margin:0!important}
    .section-title{padding-bottom:18px!important;margin-bottom:18px!important;border-bottom:1px solid rgba(255,255,255,.08)!important}.section-title .muted{font-size:13px!important;margin-top:5px!important}.field{margin:0 0 14px!important;gap:6px!important}.field label{font-size:12px!important;font-weight:700!important;letter-spacing:.01em!important;color:#aeb8c8!important}
    input,textarea,select{background:#0b1019!important;border-color:rgba(255,255,255,.10)!important;border-radius:11px!important;color:#f8fafc!important;min-height:44px!important;outline:none!important;transition:border-color .15s,box-shadow .15s!important}textarea{min-height:104px!important;resize:vertical!important}input:focus,textarea:focus,select:focus{border-color:rgba(216,179,106,.60)!important;box-shadow:0 0 0 3px rgba(216,179,106,.10)!important}
    .btn{min-height:42px!important;border-radius:11px!important;font-size:13px!important;font-weight:700!important}.btn-primary{box-shadow:0 8px 22px rgba(216,179,106,.12)!important}.grid2{gap:14px!important}
    .edit-card{padding:18px!important;margin:12px 0 0!important;border-radius:16px!important;background:rgba(255,255,255,.025)!important;border-color:rgba(255,255,255,.09)!important}.edit-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding-bottom:12px;margin-bottom:13px;border-bottom:1px solid rgba(255,255,255,.07)}.edit-card-head strong{font-size:15px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status-on,.status-off{font-size:11px;font-weight:800;padding:5px 8px;border-radius:999px;white-space:nowrap}.status-on{color:#79e2a1;background:rgba(76,175,106,.12)}.status-off{color:#aeb8c8;background:rgba(255,255,255,.07)}.link-disabled{opacity:.62}.edit-actions{justify-content:flex-end!important;flex-wrap:wrap!important;padding-top:6px!important}
    .language-tabs{gap:6px!important}.language-tabs .language-circle{width:34px!important;height:34px!important;background:rgba(255,255,255,.035)!important}.theme-editor{padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important}
    .qr-panel{display:grid!important;grid-template-columns:minmax(0,1fr) 260px!important;align-items:center!important}.qrbox{width:240px!important;min-height:240px!important;display:grid!important;place-items:center!important;border:1px dashed rgba(216,179,106,.35)!important;border-radius:18px!important;background:#fff!important;color:#111!important}.qr-actions{margin-top:16px!important}
    .admin-page .success{background:rgba(47,155,83,.12)!important;border:1px solid rgba(78,200,113,.22)!important;color:#8ee8ad!important}.admin-page .error{background:rgba(180,55,70,.12)!important;border:1px solid rgba(235,92,109,.22)!important;color:#ff9ba8!important}.admin-page .eyebrow{font-size:10px!important;letter-spacing:.18em!important}.admin-page .muted{color:#8f9bae!important}
    @media(max-width:900px){.admin-wrap{display:block!important}.admin-nav{position:sticky!important;top:0!important;z-index:30!important;width:100%!important;min-height:0!important;margin:0 0 14px!important;display:flex!important;flex-direction:row!important;overflow-x:auto!important;padding:7px!important;border-radius:15px!important;gap:5px!important}.admin-nav:before{display:none!important}.admin-nav button{width:auto!important;flex:0 0 auto!important;white-space:nowrap!important;min-height:40px!important}.admin-nav button:before{display:none!important}.admin-head{padding-top:4px!important}.panel{padding:18px!important}.qr-panel{grid-template-columns:1fr!important}.qrbox{width:100%!important;min-height:190px!important;margin-top:4px!important}}
    @media(max-width:620px){.admin-page{padding:12px!important}.admin-head{align-items:flex-start!important;flex-direction:column!important}.admin-head h1{font-size:24px!important}.admin-head-actions{width:100%!important}.admin-head-actions .btn{flex:1!important}.grid2{grid-template-columns:1fr!important}.section-title{align-items:flex-start!important;flex-direction:column!important}.edit-actions{justify-content:stretch!important}.edit-actions .btn{flex:1!important}}
  `}</style>
}
