'use client';
import { Mail, Phone, MapPin } from 'lucide-react';
import type { AdminContext, Lang, Profile } from '@/lib/types';

type Props={profile:Profile;context:AdminContext;lang:Lang;patchProfile:(p:Partial<Profile>)=>void};
const text={
 es:{title:'Información de contacto',help:'Añade los datos que quieres ofrecer a los visitantes. Cada dato puede mostrarse u ocultarse por separado.',email:'Correo electrónico',phone:'Teléfono',address:'Dirección',show:'Mostrar en la página pública'},
 en:{title:'Contact information',help:'Add the details you want to offer visitors. Each item can be shown or hidden separately.',email:'Email address',phone:'Phone',address:'Address',show:'Show on public page'},
 pt:{title:'Informações de contato',help:'Adicione os dados que deseja oferecer aos visitantes. Cada dado pode ser mostrado ou ocultado separadamente.',email:'E-mail',phone:'Telefone',address:'Endereço',show:'Mostrar na página pública'}
};
function Row({icon,label,value,visible,onValue,onVisible,placeholder}:{icon:React.ReactNode;label:string;value:string;visible:boolean;onValue:(v:string)=>void;onVisible:(v:boolean)=>void;placeholder:string}){
 return <div className="contact-row"><div className="contact-field"><div className="contact-label"><span className="contact-icon">{icon}</span><label>{label}</label></div><input value={value} onChange={e=>onValue(e.target.value)} placeholder={placeholder}/></div><label className="check-field contact-toggle"><input type="checkbox" checked={visible} onChange={e=>onVisible(e.target.checked)}/>{text.es.show}</label></div>
}
export default function ContactSection({profile,lang,patchProfile}:Props){const t=text[lang];return <div className="contact-section"><div className="contact-heading"><div><h3>{t.title}</h3><p className="muted">{t.help}</p></div></div><div className="contact-card"><div className="contact-field"><div className="contact-label"><span className="contact-icon"><Mail size={17}/></span><label>{t.email}</label></div><input type="email" value={profile.contact_email||''} onChange={e=>patchProfile({contact_email:e.target.value})} placeholder="correo@ejemplo.com"/></div><label className="check-field contact-toggle"><input type="checkbox" checked={profile.show_contact_email} onChange={e=>patchProfile({show_contact_email:e.target.checked})}/>{t.show}</label><div className="contact-field"><div className="contact-label"><span className="contact-icon"><Phone size={17}/></span><label>{t.phone}</label></div><input type="tel" value={profile.contact_phone||''} onChange={e=>patchProfile({contact_phone:e.target.value})} placeholder="(000) 000-0000"/></div><label className="check-field contact-toggle"><input type="checkbox" checked={profile.show_contact_phone} onChange={e=>patchProfile({show_contact_phone:e.target.checked})}/>{t.show}</label><div className="contact-field"><div className="contact-label"><span className="contact-icon"><MapPin size={17}/></span><label>{t.address}</label></div><textarea value={profile.contact_address||''} onChange={e=>patchProfile({contact_address:e.target.value})} placeholder={lang==='es'?'Dirección de la iglesia':lang==='pt'?'Endereço da igreja':'Church address'}/></div><label className="check-field contact-toggle"><input type="checkbox" checked={profile.show_contact_address} onChange={e=>patchProfile({show_contact_address:e.target.checked})}/>{t.show}</label></div></div>}
