'use client';
import { Instagram, Facebook, Youtube, MessageCircle, Heart, CalendarDays, Globe, ArrowUpRight, MoreHorizontal, Link as LinkIcon, BookOpen, Users, Play, Share2, Flag, LogIn, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { LinkItem, Profile } from '@/lib/types';
import { t, uiText } from '@/lib/i18n';
import { useLanguage } from '@/components/LanguageProvider';

const icons: Record<string, React.ReactNode> = { instagram:<Instagram size={22}/>, facebook:<Facebook size={22}/>, youtube:<Youtube size={22}/>, whatsapp:<MessageCircle size={22}/>, donation:<Heart size={22}/>, calendar:<CalendarDays size={22}/>, website:<Globe size={22}/>, link:<LinkIcon size={22}/>, bible:<BookOpen size={22}/>, community:<Users size={22}/>, play:<Play size={22}/> };
function iconFor(v:string){return icons[v?.toLowerCase()] ?? <LinkIcon size={22}/>;}
const defaultPalette={accent:'#d8b36a',background:'#05080d',surface:'#111923',text:'#ffffff',muted:'#b8c1d0',primary:'#d8b36a'};

export default function PublicPage({profile,links,origin:_origin}:{profile:Profile;links:LinkItem[];origin:string}){
 const {lang,cycleLang}=useLanguage();
 const [menuOpen,setMenuOpen]=useState(false),[reportOpen,setReportOpen]=useState(false),[reportText,setReportText]=useState('');
 function sharePage(){const url=window.location.href;const title=t(profile.name,profile.translations,lang,'name');if(navigator.share)navigator.share({title,url}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(url).catch(()=>{});else window.prompt(ui.copyLink,url);setMenuOpen(false)}
 function openReport(){setReportOpen(true);setMenuOpen(false)}
 function submitReport(){const subject=encodeURIComponent(`${ui.reportTitle} - ${t(profile.name,profile.translations,lang,'name')}`);const body=encodeURIComponent(reportText||ui.reportDefault);window.location.href=`mailto:?subject=${subject}&body=${body}`;setReportOpen(false);setReportText('')}
 const palette={...defaultPalette,...(profile.palette||{}),accent:profile.palette?.accent||profile.accent_color||defaultPalette.accent};
 const template=profile.template||'elegant';
 const activeLinks=links.filter(x=>x.active).sort((a,b)=>a.sort_order-b.sort_order);
 const socials=activeLinks.filter(x=>['instagram','facebook','youtube','whatsapp'].includes(x.icon?.toLowerCase())).slice(0,5);
 const values=t(profile.values_text,profile.translations,lang,'values').split('|').map(v=>v.trim()).filter(Boolean);
 const ui=useMemo(()=>({
   kicker:t(profile.kicker,profile.translations,lang,'kicker')||uiText({es:'UN LUGAR PARA TODOS',en:'A PLACE FOR EVERYONE',pt:'UM LUGAR PARA TODOS'},lang),
   values,
   follow:uiText({es:'SÍGUENOS EN REDES SOCIALES',en:'FOLLOW US ON SOCIAL MEDIA',pt:'SIGA-NOS NAS REDES SOCIAIS'},lang),
   featured:uiText({es:'DESTACADO',en:'FEATURED',pt:'DESTAQUE'},lang), now:uiText({es:'Ver ahora',en:'View now',pt:'Ver agora'},lang),
   quote:t(profile.quote_text,profile.translations,lang,'quote')||'“Todo es posible para el que cree.”', verse:t(profile.quote_verse,profile.translations,lang,'verse')||'Marcos 9:23',
   changeLanguage:uiText({es:'Cambiar idioma',en:'Change language',pt:'Mudar idioma'},lang), currentLanguage:uiText({es:'Idioma actual',en:'Current language',pt:'Idioma atual'},lang), moreOptions:uiText({es:'Más opciones',en:'More options',pt:'Mais opções'},lang), share:uiText({es:'Compartir',en:'Share',pt:'Compartilhar'},lang), report:uiText({es:'Reportar un problema',en:'Report a problem',pt:'Relatar um problema'},lang), login:uiText({es:'Login',en:'Login',pt:'Entrar'},lang), reportTitle:uiText({es:'Reportar un problema',en:'Report a problem',pt:'Relatar um problema'},lang), reportPlaceholder:uiText({es:'Cuéntanos qué está pasando...',en:'Tell us what is wrong...',pt:'Conte-nos o que está acontecendo...'},lang), cancel:uiText({es:'Cancelar',en:'Cancel',pt:'Cancelar'},lang), send:uiText({es:'Enviar reporte',en:'Send report',pt:'Enviar relatório'},lang), verified:uiText({es:'Cuenta verificada',en:'Verified account',pt:'Conta verificada'},lang), mainLinks:uiText({es:'Enlaces principales',en:'Main links',pt:'Links principais'},lang), logoAlt:uiText({es:'Logo de',en:'Logo of',pt:'Logo de'},lang), footerFallback:uiText({es:'Más que una iglesia, una familia.',en:'More than a church, a family.',pt:'Mais que uma igreja, uma família.'},lang), copyLink:uiText({es:'Copiar enlace',en:'Copy link',pt:'Copiar link'},lang), reportDefault:uiText({es:'Quiero reportar un problema en esta página.',en:'I want to report a problem on this page.',pt:'Quero relatar um problema nesta página.'},lang)
 }),[lang,profile.kicker,profile.values_text,profile.quote_text,profile.quote_verse,profile.translations,values]);
 return <main className={`page-bg template-${template} modern-mobile-page`} style={{'--accent':palette.accent,'--page-bg':palette.background,'--surface':palette.surface,'--text':palette.text,'--muted':palette.muted,'--primary':palette.primary} as React.CSSProperties}>
  <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
  <div className="public-container app-public-container">
   <div className="topbar app-topbar"><button type="button" className="language-circle public-language" onClick={cycleLang} title={ui.changeLanguage} aria-label={`${ui.changeLanguage}. ${ui.currentLanguage}: ${lang.toUpperCase()}`}>{lang.toUpperCase()}</button><div className="more-wrap"><button type="button" className="more" onClick={()=>setMenuOpen(v=>!v)} aria-label={ui.moreOptions} aria-expanded={menuOpen}><MoreHorizontal size={20}/></button>{menuOpen&&<><button className="menu-backdrop" aria-label={ui.cancel} onClick={()=>setMenuOpen(false)}/><div className="more-menu"><button type="button" onClick={sharePage}><Share2 size={17}/><span>{ui.share}</span></button><button type="button" onClick={openReport}><Flag size={17}/><span>{ui.report}</span></button><a href="/admin" onClick={()=>setMenuOpen(false)}><LogIn size={17}/><span>{ui.login}</span></a></div></>}</div></div>
   <section className="profile app-hero" id="inicio"><div className="profile-mark"><div className="logo">{profile.logo_url?<img src={profile.logo_url} alt={`${ui.logoAlt} ${t(profile.name,profile.translations,lang,'name')}`}/>:<span>{profile.name.slice(0,2).toUpperCase()}</span>}</div><span className="verified" aria-label={ui.verified}>✓</span></div><div className="brand-kicker">{ui.kicker}</div><h1>{t(profile.name,profile.translations,lang,'name')}</h1>{t(profile.handle,profile.translations,lang,'handle')&&<div className="handle">{t(profile.handle,profile.translations,lang,'handle')}</div>}{t(profile.bio,profile.translations,lang,'bio')&&<p className="bio">{t(profile.bio,profile.translations,lang,'bio')}</p>}<div className="mini-values">{ui.values.map((v,i)=><span key={i}>{v}</span>).flatMap((node,i)=>i<ui.values.length-1?[node,<i key={`dot-${i}`}>•</i>]:[node])}</div></section>
   <section className="mobile-app-summary"><div><span className="app-eyebrow">{ui.featured}</span><h2>{ui.kicker}</h2><p>{t(profile.bio,profile.translations,lang,'bio')||ui.footerFallback}</p></div></section>
   <section className="links app-links" id="enlaces" aria-label={ui.mainLinks}><div className="app-section-heading"><div><span>Enlaces</span><h2>{ui.mainLinks}</h2></div></div>{activeLinks.map((link,index)=><a className={`link app-link ${index===0?'link-primary':''}`} href={link.url} target="_blank" rel="noreferrer" key={link.id}><span className="icon">{iconFor(link.icon)}</span><span className="link-content"><span className="link-title">{t(link.title,link.translations,lang,'title')}</span>{t(link.subtitle,link.translations,lang,'subtitle')&&<span className="link-sub">{t(link.subtitle,link.translations,lang,'subtitle')}</span>}</span><span className="arrow"><ArrowUpRight size={20}/></span></a>)}</section>
   {profile.featured_url&&profile.featured_title&&<section id="destacado"><a className="featured app-featured" href={profile.featured_url} target="_blank" rel="noreferrer">{profile.featured_image_url?<img src={profile.featured_image_url} alt=""/>:<div className="featured-art"><span>✦</span></div>}<div><small>{ui.featured}</small><h2>{t(profile.featured_title,profile.translations,lang,'title')}</h2><span className="featured-cta">{ui.now} <ArrowUpRight size={15}/></span></div></a></section>}
   {socials.length>0&&<div className="social-block app-social-block"><div className="section-label"><span/>{ui.follow}<span/></div><div className="socials">{socials.map(link=><a className="social" href={link.url} target="_blank" rel="noreferrer" key={link.id} aria-label={t(link.title,link.translations,lang,'title')}>{iconFor(link.icon)}</a>)}</div></div>}
   <section className="quote app-quote"><div className="quote-line"/><p>{ui.quote}</p><small>{ui.verse}</small></section><div className="footer">{t(profile.footer_text,profile.translations,lang,'footer')||ui.footerFallback}</div>
   {reportOpen&&<div className="report-overlay" role="dialog" aria-modal="true" aria-labelledby="report-title"><div className="report-card"><div className="report-head"><h2 id="report-title">{ui.reportTitle}</h2><button type="button" className="report-close" onClick={()=>setReportOpen(false)} aria-label={ui.cancel}><X size={19}/></button></div><textarea value={reportText} onChange={e=>setReportText(e.target.value)} placeholder={ui.reportPlaceholder} rows={5}/><div className="report-actions"><button type="button" className="btn btn-secondary" onClick={()=>setReportOpen(false)}>{ui.cancel}</button><button type="button" className="btn btn-primary" onClick={submitReport}>{ui.send}</button></div></div></div>}
  </div>
  <style jsx global>{`
   .modern-mobile-page{--app-radius:20px}
   .modern-mobile-page .app-topbar{height:54px}
   .modern-mobile-page .app-hero{padding-top:10px}
   .modern-mobile-page .app-hero .profile-mark{margin-bottom:14px}
   .modern-mobile-page .app-hero h1{font-family:'DM Sans',Arial,sans-serif;font-size:clamp(30px,7vw,40px);font-weight:700;letter-spacing:-.045em}
   .modern-mobile-page .app-hero .bio{max-width:470px}
   .modern-mobile-page .mobile-app-summary{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:25px 0 12px;padding:18px 19px;border:1px solid color-mix(in srgb,var(--text) 10%,transparent);border-radius:var(--app-radius);background:color-mix(in srgb,var(--surface) 90%,transparent);box-shadow:0 18px 45px rgba(0,0,0,.14)}
   .modern-mobile-page .mobile-app-summary>div{min-width:0}.modern-mobile-page .app-eyebrow,.modern-mobile-page .app-section-heading span{font-size:9px;letter-spacing:.17em;text-transform:uppercase;color:var(--accent);font-weight:800}.modern-mobile-page .mobile-app-summary h2{font-size:19px;margin:5px 0 4px;letter-spacing:-.02em}.modern-mobile-page .mobile-app-summary p{margin:0;color:var(--muted);font-size:12px;line-height:1.45;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
   .modern-mobile-page .app-links{margin-top:16px}.modern-mobile-page .app-section-heading{display:flex;justify-content:space-between;align-items:end;margin:0 2px 10px}.modern-mobile-page .app-section-heading h2{font-size:18px;margin:3px 0 0;letter-spacing:-.02em}.modern-mobile-page .app-link{min-height:74px;border-radius:var(--app-radius);padding:13px 14px;background:color-mix(in srgb,var(--surface) 94%,transparent);box-shadow:0 10px 30px rgba(0,0,0,.12)}.modern-mobile-page .app-link .icon{width:46px;height:46px;border-radius:14px}.modern-mobile-page .app-link .link-title{font-size:15px}.modern-mobile-page .app-link.link-primary{background:var(--primary);border-color:color-mix(in srgb,var(--primary) 80%,white 20%);box-shadow:0 12px 32px color-mix(in srgb,var(--primary) 16%,transparent)}
   .modern-mobile-page .app-featured{margin-top:12px;border-radius:var(--app-radius);padding:14px}.modern-mobile-page .app-featured img,.modern-mobile-page .app-featured .featured-art{width:82px;height:82px;flex-basis:82px;border-radius:16px}.modern-mobile-page .app-social-block{margin-top:30px}.modern-mobile-page .app-quote{padding-bottom:14px}
   @media(max-width:640px){
    .modern-mobile-page .public-container{padding-left:13px;padding-right:13px}
    .modern-mobile-page .profile-mark{width:96px;height:96px}.modern-mobile-page .logo{width:92px;height:92px}
    .modern-mobile-page .brand-kicker{font-size:9px;letter-spacing:.26em}.modern-mobile-page .bio{font-size:13px;line-height:1.5}
    .modern-mobile-page .mobile-app-summary{margin-top:20px;padding:16px;border-radius:18px}.modern-mobile-page .mobile-app-summary h2{font-size:17px}.modern-mobile-page .app-link{min-height:70px;border-radius:18px}.modern-mobile-page .app-featured{border-radius:18px}.modern-mobile-page .social{width:44px;height:44px}
   }
  `}</style>
 </main>;
}
