'use client';
import { QRCodeSVG } from 'qrcode.react';
import { Instagram, Facebook, Youtube, MessageCircle, Heart, CalendarDays, Globe, ArrowUpRight, MoreHorizontal, Link as LinkIcon } from 'lucide-react';
import type { LinkItem, Profile } from '@/lib/types';

const icons: Record<string, React.ReactNode> = { instagram:<Instagram size={20}/>, facebook:<Facebook size={20}/>, youtube:<Youtube size={20}/>, whatsapp:<MessageCircle size={20}/>, donation:<Heart size={20}/>, calendar:<CalendarDays size={20}/>, website:<Globe size={20}/>, link:<LinkIcon size={20}/> };
function iconFor(v:string){return icons[v.toLowerCase()] ?? <span>{v || '🔗'}</span>}
export default function PublicPage({profile,links,origin}:{profile:Profile;links:LinkItem[];origin:string}){
 const publicUrl=`${origin}/${profile.slug}`; const accent=profile.accent_color||'#d8b36a';
 return <main className="page-bg" style={{'--accent':accent} as React.CSSProperties}><div className="public-container"><div className="topbar"><button className="more" aria-label="Más opciones"><MoreHorizontal size={19}/></button></div><section className="profile"><div className="logo">{profile.logo_url?<img src={profile.logo_url} alt="Logo"/>:<span>{profile.name.slice(0,2).toUpperCase()}</span>}</div><h1>{profile.name} <span className="verified">✓</span></h1>{profile.handle&&<div className="handle">{profile.handle}</div>}{profile.bio&&<p className="bio">{profile.bio}</p>}</section><section className="links">{links.filter(x=>x.active).sort((a,b)=>a.sort_order-b.sort_order).map(link=><a className="link" href={link.url} target="_blank" rel="noreferrer" key={link.id}><span className="icon">{iconFor(link.icon)}</span><span className="link-content"><span className="link-title">{link.title}</span>{link.subtitle&&<span className="link-sub">{link.subtitle}</span>}</span><span className="arrow"><ArrowUpRight size={19}/></span></a>)}</section>{profile.featured_url&&profile.featured_title&&<a className="featured" href={profile.featured_url} target="_blank" rel="noreferrer">{profile.featured_image_url&&<img src={profile.featured_image_url} alt=""/>}<div><small>DESTACADO</small><h2>{profile.featured_title}</h2></div></a>}<div className="socials">{links.filter(x=>x.active&&['instagram','facebook','youtube','whatsapp'].includes(x.icon.toLowerCase())).slice(0,4).map(link=><a className="social" href={link.url} target="_blank" rel="noreferrer" key={link.id} aria-label={link.title}>{iconFor(link.icon)}</a>)}</div><section className="qr"><h3>Comparte nuestra página</h3><p>Escanea el código QR para acceder rápidamente.</p><div className="qrbox"><QRCodeSVG value={publicUrl} includeMargin={false}/></div></section><div className="footer">{profile.footer_text||''}</div></div></main>
}
