'use client';
import { useEffect, useState } from 'react';
import { Shield, Crown, UserCog, Pencil, Save } from 'lucide-react';
import { supabaseBrowser } from '@/lib/supabase';
import { useLanguage } from '@/components/LanguageProvider';
import type { AdminContext, Lang } from '@/lib/types';

type Member={id:string;user_id:string;email:string|null;display_name:string|null;role:'superadmin'|'admin'|'editor';is_primary:boolean};
const words={es:{team:'Equipo',title:'Equipo y permisos',help:'Administra quién puede entrar al panel y qué nivel de acceso tiene.',loading:'Cargando miembros…',member:'Miembro',account:'Cuenta autenticada',primary:'Superadmin principal',editor:'Editor',admin:'Administrador',superadmin:'Superadmin',saved:'Guardando',updated:'✓ Rol actualizado',no:'No tienes permiso para administrar miembros.',wide:'Acceso administrativo amplio y gestión de superadmins.',manage:'Gestiona contenido, enlaces y configuración permitida.',limited:'Acceso limitado a las tareas asignadas.'},en:{team:'Team',title:'Team & permissions',help:'Manage who can access the panel and their access level.',loading:'Loading members…',member:'Member',account:'Authenticated account',primary:'Primary superadmin',editor:'Editor',admin:'Administrator',superadmin:'Superadmin',saved:'Saving',updated:'✓ Role updated',no:'You do not have permission to manage members.',wide:'Broad administrative access and superadmin management.',manage:'Manages content, links, and allowed settings.',limited:'Limited access to assigned tasks.'},pt:{team:'Equipe',title:'Equipe e permissões',help:'Gerencie quem pode acessar o painel e seu nível de acesso.',loading:'Carregando membros…',member:'Membro',account:'Conta autenticada',primary:'Superadmin principal',editor:'Editor',admin:'Administrador',superadmin:'Superadmin',saved:'Salvando',updated:'✓ Função atualizada',no:'Você não tem permissão para administrar membros.',wide:'Amplo acesso administrativo e gestão de superadmins.',manage:'Gerencia conteúdo, links e configurações permitidas.',limited:'Acesso limitado às tarefas atribuídas.'}};
export default function TeamAdmin({context}:{context:AdminContext}){const sb=supabaseBrowser();const {lang}=useLanguage();const w=words[lang];const [members,setMembers]=useState<Member[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState<string|null>(null);const [msg,setMsg]=useState('');const canManage=!!context.permissions.manage_members;
 useEffect(()=>{if(!canManage){setLoading(false);return}(async()=>{const {data,error}=await sb.rpc('get_org_members_admin',{p_organization_id:context.organization_id});if(error)setMsg(`Error: ${error.message}`);else setMembers((data||[]) as Member[]);setLoading(false)})()},[context.organization_id,canManage]);
 async function changeRole(userId:string,role:Member['role']){setSaving(userId);setMsg('');const {error}=await sb.rpc('update_org_member_role',{p_organization_id:context.organization_id,p_user_id:userId,p_role:role});if(error)setMsg(`Error: ${error.message}`);else{setMembers(ms=>ms.map(m=>m.user_id===userId?{...m,role}:m));setMsg(w.updated)}setSaving(null)}
 if(!canManage)return <section className="panel"><h2>{w.team}</h2><p className="muted">{w.no}</p></section>;
 return <section className="panel team-panel"><div className="section-title"><div><h2><Shield size={19}/>{w.title}</h2><p className="muted">{w.help}</p></div></div>{loading?<p className="muted">{w.loading}</p>:<div className="member-list">{members.map(m=><div className="member-row" key={m.id}><div className="member-avatar">{m.is_primary?<Crown size={17}/>:m.role==='admin'?<UserCog size={17}/>:<Pencil size={17}/>}</div><div className="member-info"><strong>{m.display_name||w.member}</strong><span>{m.email||w.account}</span></div><div className="member-role">{m.is_primary?<span className="primary-badge">{w.primary}</span>:<select value={m.role} disabled={saving===m.user_id||(!context.permissions.manage_superadmins&&m.role==='superadmin')} onChange={e=>changeRole(m.user_id,e.target.value as Member['role'])}><option value="editor">{w.editor}</option><option value="admin">{w.admin}</option>{context.permissions.manage_superadmins&&<option value="superadmin">{w.superadmin}</option>}</select>}</div>{!m.is_primary&&saving===m.user_id&&<span className="saving-mini"><Save size={14}/>{w.saved}</span>}</div>)}</div>}{msg&&<p className={msg.startsWith('Error')?'error':'success'}>{msg}</p>}<div className="role-help"><div><b>{w.superadmin}</b><span>{w.wide}</span></div><div><b>{w.admin}</b><span>{w.manage}</span></div><div><b>{w.editor}</b><span>{w.limited}</span></div></div></section>;
}
